# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_keywordset'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceIdentifier',
            fields=[
                ('identifier', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.DataSource')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='events.Place')),
            ],
        ),
        migrations.AlterField(
            model_name='keywordset',
            name='usage',
            field=models.SmallIntegerField(choices=[(1, 'any'), (2, 'keyword'), (3, 'audience')], default=1, verbose_name='Intended keyword usage'),
        ),
        migrations.AlterUniqueTogether(
            name='placeidentifier',
            unique_together=set([('data_source', 'identifier')]),
        ),
    ]
